### ISSUE TITLE
nwnsc crashes with SIGILL on some invalid scripts

### ISSUE THREAD

**Issue by squattingmonk** [nwneetools/nwnsc#10]
To reproduce, attempt to compile the following script:
```
void main()
{
    AssignCommand(OBJECT_SELF, TRUE);
}
```
**Actual behavior:** nwnsc crashes with SIGILL error code.
**Expected behavior:** nwnsc emits a useful error and proceeds to the next script.

**OS:** Arch Linux 64-bit

**Comment by jakkn** [comment]
Hi! Thanks for the bug report. I'm unable to fix this myself for the time being. Maybe @virusman has time. PRs are always welcome :slightly_smiling_face:

**Comment by jd28** [comment]
I was just about to report the same issue.  It seems like the typechecker just falls over on mismatched parameter types.  An error message is generated with `string t = 1;`

```c++
int thisisatest(int arg1, string arg2, int optional=1)
{
    return IntToString(arg1) == arg2;
}

void main()
{
    string t = 1;
    thisisatest("hello", "world");
}
```
It still occurs even after the error on line 8.  No clue if any of this will help track down the issue or not.

**OS**: WSL2

**Comment by virusman** [comment]
I can't reproduce it on Mac, here is what I get:
```
Compiling: test.nss
test.nss(8): Error: NSC1053: Declaration and initialization value type mismatch for variable "t"


test.nss(9): Error: NSC1002: Type mismatch in parameter 1 ("arg1") in call to "thisisatest": Expected type "int", but got type "string"


Compilation aborted with errors.

Total Execution time = 0.1480 seconds
```

**Comment by virusman** [comment]
Are you using the latest version, 1.1.1?

**Comment by jd28** [comment]
Weird.  I built from source on WSL2 (Ubuntu).  On Manjaro with both version 1.0.0 (must have been from the vault) and just tried 1.1.1 (from releases here), I get same the illegal hardware instruction.  I'll try on windows and report back.

**Comment by jd28** [comment]
Works fine on Windows, same output as Mac.

**Comment by virusman** [comment]
Which compiler are you using on Linux?

**Comment by jd28** [comment]
It was probably 9.3 on WSL2 (Ubuntu 20.04), but it happens with release builds that I haven't compiled on my native Linux setup (I can't build it at all there: https://github.com/nwneetools/nwnsc/issues/13)

**Comment by squattingmonk** [comment]
I can't compile it anymore (I think due to #13; I'm using bison 3.6.3), but the 1.1.1 release binary gives the same error on Linux.
