### ISSUE TITLE
[bison] v3.6 seems to have changed things again.

### ISSUE THREAD

**Issue by jd28** [nwneetools/nwnsc#13]
These typedefs don't seem like they're going to work:
https://github.com/nwneetools/nwnsc/blob/5300b86dd3980a5e565a474aa71880df65ee6511/_NscLib/NscCompat.h#L8-L11

**Comment by jakkn** [comment]
I've been on vacation so I haven't had eyes on the project for a couple of weeks. How urgent is this?

**Comment by jd28** [comment]
Not really urgent at all, rolling linux distros like Arch & Manjaro (maybe
Fedora) have already upgraded their Bison versions.  One can still build it
in docker fine.  It will become an issue at some point tho when whatever
distro the docker image uses is upgraded.  I think the fix is just adding
more typedefs, but I'm really not at all familiar with Bison.

**Comment by jakkn** [comment]
I see. I can't tell what version of Bison the [runners](https://docs.github.com/en/actions/reference/software-installed-on-github-hosted-runners) ship with, but none of them are rolling releases so we should be fine for a while. The same applies to the docker image. Do you have a link to a bison resource that documents the change, and do you have the build error as well?

**Comment by jd28** [comment]
Attached is the build error.  I made a few small modifications to better isolate the issue, so this isn't exactly what you'd see if you built with gcc 10.1 and Bison 3.6.2. [error_message.txt](https://github.com/nwneetools/nwnsc/files/4883799/error_message.txt)

I couldn't say from looking at the Bison changelog where the issue started, sorry.  And so much of the history of this code base has been lost it's hard to tell when and why things were changed, it might have been operating on deprecated time.

Attached also is a diff that allows the thing to build, but with the huuuuuuuuuuuuuuge caveat that this is an untested guess as to how to fix the issue: [diff.txt](https://github.com/nwneetools/nwnsc/files/4884176/diff.txt)

**Comment by meaglyn** [comment]
I posted a PR that fixes this. Based on jd28's research.  It works fine in my nwnnsscomp tree.  Not as well tested with nwnsc since I don't use it and it doesn't fit in my scripts as well.  But that part of the code is still the same between the two versions. Fwiw...
