### ISSUE TITLE
Undeclared identifier "GetCurrentlyRunningEvent"

### ISSUE THREAD

**Issue by julien-lecomte** [nwneetools/nwnsc#23]
With latest version:

Error: nx_event.nss(124)
         ... NSC1020
         ... Undeclared identifier "GetCurrentlyRunningEvent"

**Comment by tinygiant98** [comment]
Nwscript functions are not organic to nwnsc. That function is not in stable yet. Do you have the dev version with the correct nwscript.nss available on your system and is nwnsc pointed to it with the -n argument?
