### ISSUE TITLE
Unable to open the include file "nw_inc_nui"

### ISSUE THREAD

**Issue by Kaikas** [nwneetools/nwnsc#30]
When i run 
```
docker run --rm -it -v "$(pwd):/tmp" nwneetools/nwnsc
```
on nui_test.nss
```c
#include "nw_inc_nui"
void main() {
}
```
i get
```
Loading base game resources...

Home Path - ~/Documents/Neverwinter Nights/

Compiling: nui_test.nss
nui_test.nss(1): Error: NSC1085: Unable to open the include file "nw_inc_nui"


Compilation aborted with errors.

Error: Failed to process file ./nui_test.nss.

Stopping processing on first error.

1 error(s); see above for context.

Processing aborted.

Total Execution time = 0.1430 seconds
```

I don't have nwn installed on that machine as i use the nwnx docker image. Do i need to install nwn so ~/Documents/Neverwinter Nights/ is valid?

**Comment by DMHoodoo** [comment]
You do require a NwN installation I believe as nw_inc_nui is included with the base-game.

**Comment by jakkn** [comment]
Hi @Kaikas, sorry for the late response, I don't use this compiler much myself anymore so I don't keep up to date here as often as I should.

The image ships with the necessary resources to compile, so you're using it correctly. The image is simply outdated as it hasn't been built after NUI was released. I bet the autobuild integration broke down when Docker Hub changed things up last summer. I'll try to initiate a new build manually.

**Comment by jakkn** [comment]
@Kaikas it appears that all build infrastructure has been removed from the free tier on docker hub, so there is no quick fix to this problem. However, if you build the image locally (e.g. with `docker build . -t nwnsc:local`) you can build nui scripts with the command you specified above (and using the appropriate image tag).

Closing in favor of #31.
