### ISSUE TITLE
NWN:EE Development v87.8193.35-36 with nwnsc v1.1.3: Error: NSC1020: Undeclared identifier "LOCATION_INVALID"

### ISSUE THREAD

**Issue by prwo2** [nwneetools/nwnsc#37]
Using: nwnsc version 1.1.3 - built Apr  2 2022 01:02:20

Updated via Beamdog Client to the latest NWN:EE Development release: [v87.8193.35-36](https://nwn.beamdog.net/docs/#87819335-36---2023-03-14)
According to the changelog, this new release contains a lot of new script functions as well as new constants and types.

Wenn I compile an nss with nwnsc v1.1.3 I get the following error:
`nwscript.nss(8204): Error: NSC1020: Undeclared identifier "LOCATION_INVALID"`

I assume this is because nwnsc v1.1.3 doesn't support the recently introduced types etc.

**Comment by tinygiant98** [comment]
That is correct. There are some unofficial releases hanging about until we can push the new version. What's your OS?

**Comment by prwo2** [comment]
My OS is Windows 10 Pro

**Comment by tinygiant98** [comment]
@prwo2 If you're on discord, you can go here <https://discord.com/channels/382306806866771978/1085063853622165556/1085063861037699174>  I compiled an unofficial version that allows the new constants, but it does not yet do the strings-in-case-statement.

**Comment by prwo2** [comment]
I downloaded the latest release pack nwnsc-win-v1.1.4.zip and compiling with [v87.8193.35-36](https://nwn.beamdog.net/docs/#87819335-36---2023-03-14) works now.

One thing I noticed about this release package v1.1.4 though: the nwnsc.exe still calls itself v1.1.3:
`Usage: version 1.1.3 - built Mar 23 2023 21:12:43`

**Comment by tinygiant98** [comment]
@prwo2 Yes, that was my mistake.  We're working a fix for the `-c` option, which was also introduced in 1.1.4, and the new build (which will probably be 1.1.5) will include the correct versioning.  Thanks!

**Comment by prwo2** [comment]
Thank you.
nwnsc.exe from newest release package nwnsc-win-v1.1.5.zip now prompts the version as it should:
`Usage: version 1.1.5 - built Mar 25 2023 01:34:22`
