### ISSUE TITLE
Bison missing during build

### ISSUE THREAD

**Issue by mhekel** [nwneetools/nwnsc#42]
Hi so I'm running a full Linuz kernel with wsl2/Unbuntu22.04

everything I've needed to install is going rather smoothly - occasional missing dep's such as this: 
``` 
user@Mr-Server:~/nwnsc$ ./scripts/buildnwnsc.sh
./scripts/buildnwnsc.sh: line 3: /hbb_exe/activate: No such file or directory
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find BISON (missing: BISON_EXECUTABLE)
CMake Error at CMakeLists.txt:38 (message):
  Cannot find bison, need bison installed to generate Parser/Lexer


-- Configuring incomplete, errors occurred!
See also "/home/user/nwnsc/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'all'.  Stop.
``` 

I've attached the cmakeoutput log
[CMakeOutput.log](https://github.com/nwneetools/nwnsc/files/15047372/CMakeOutput.log)

**Comment by squattingmonk** [comment]
Did you install bison?

**Comment by mhekel** [comment]
yes i was able to - finally!!!! what I learned from having to reinstall a couple of times due to accidental deletion of important folders - while the support is available for windows ( I was using git-bash) -  it was a breeze installing nim/choosenim and nasher (loved how it took care of neverwinter.nim as well - on a full linux kernal (wsl2/Ubuntu) - i don't (need) tp use Docker with wsl2 :-) (so far)..
