### ISSUE TITLE
64 bit binaries

### ISSUE THREAD

**Issue by hendrikgit** [nwneetools/nwnsc#5]
If it were possible to compile 64 bit binaries of nwnsc for linux but even more importantly for macos, that would be great.

**Comment by jakkn** [comment]
This is high priority, I just need to make some time. PRs welcome if I take too long.

**Comment by virusman** [comment]
Released 64-bit binaries in 1.1.1: https://github.com/nwneetools/nwnsc/releases/tag/v1.1.1
