### ISSUE TITLE
Steam path uses MacOS location regardless of OS

### ISSUE THREAD

**Issue by squattingmonk** [nwneetools/nwnsc#8]
When given the `-l` flag, `nwnsc` uses `$HOME/Library/Application Support/Steam/steamapps/common/Neverwinter Nights/` regardless of OS. This location is only valid for MacOS installs. The correct locations for the other platforms are:
- Linux: `$HOME/.local/share/Steam/steamapps/common/Neverwinter Nights`
- Windows: `%PROGRAMFILES(X86)%\Steam\steamapps\common\Neverwinter Nights`

**Comment by jakkn** [comment]
Fixed in #9
